### ISSUE TITLE
Crear un Contributing.md

### ISSUE THREAD

**Issue by afk-mario** [indi-es/estudios#18]
Explicar como contribuir a la lista de estudios

**Comment by NikanCode** [comment]
En la rama https://github.com/indi-es/estudios/tree/contributing.md estoy trabajando en una versión del archivo.

**Comment by AlainPlusPlus** [comment]
@NikanCode, me esta gustando mucho la documentación para contribuir.
Unos puntos a considerar acerca del formato de los datos:
- `¿Cómo contribuir?` se podría agregar en la `Tabla de contenido`.
- `Lo que no`, no se si sea necesario.
- La tabla de atributos es muy útil, sólo hay que cambiar la definición de `inactive` = `true` si está **inactivo**, `false` si está activo. 
- El [formato](https://user-images.githubusercontent.com/24782574/112930197-16cf8800-90d7-11eb-86ab-3762c3bf3fac.png) probablemente va a estar cambiando en el futuro. Tal vez esto se podría poner como código en lugar de imagen:
```
{
      "name": "1 Simple Game",
      "country": "México",
      "state": "Jalisco",
      "city": "Zapopan",
      "type": "studio",
      "tags": [],
      "inactive": false,
      "last_time_active": "2021-02-21T23:54:02.104Z",
      "twitter": "https://twitter.com/1simplegame",
      "facebook": "https://www.facebook.com/1SimpleGame",
      "instagram": "",
      "website": "https://1simplegame.com/"
    }
```

**Comment by NikanCode** [comment]
Ohh, gracias en un rato le voy a seguir, gracias por tus observaciones @AlainPlusPlus. Lo de lo que no es que lo tome de base del discord, pero creo que si son cosas distintas, lo principal era saber si más o menos es lo que esta pensando en el issue
