### ISSUE TITLE
Evitar que el GH action cheque estudios que marcamos manualmente como no activos.

### ISSUE THREAD

**Issue by afk-mario** [indi-es/estudios#25]

**Comment by AlainPlusPlus** [comment]
@afk-mario, esta sería mi propuesta: **JSON ->** Markdown*  **-> site-checker**

La otra opción que pensé: **JSON -> site-checker  ->** Markdown*  pero aquí se crearía el Markdown cada vez que se checan los sitios (4hrs) y la refactorización sería mayor.

_*Markdown sería el README.md con la lista ya curada de los estudios manualmente marcados como activos en el JSON._

**Comment by afk-mario** [comment]
Creo que el markdown no tendría que auto generarse cada vez que corramos el site-checker, generamos el badge y el markdown solo tiene una referencia, creo que prefiero ver la manera de que seas así considerando que nuestro source of truth es el JSON

**Comment by AlainPlusPlus** [comment]
¡Perfecto!👌Entonces las dos GH action quedarían así:
- **JSON -> Markdown** _cada que se modifique el JSON (cuando hay un merge de PRs)._
- **Markdown -> site-checker** _cada cuatro horas (Cron job)._

**Comment by afk-mario** [comment]
Yes, ando preparando un PR para esto

**Comment by AlainPlusPlus** [comment]
En el script que convierte a Markdown genera todo en [estudios.md](https://github.com/indi-es/estudios/blob/main/estudios.md). Sería cuestion de cambiarlo a README.md y agregarle lo del badge al inicio.

**Comment by afk-mario** [comment]
Listo, se cerraría con https://github.com/indi-es/estudios/pull/28
