### ISSUE TITLE
Arreglar duplicados en site-checker

### ISSUE THREAD

**Issue by afk-mario** [indi-es/estudios#3]
La actual función en el [site-checker](https://github.com/indi-es/estudios/blob/main/.github/site-checker/index.js#L19) para agarrar todos los links de el README genera duplicados, creo que hay un mejor algoritmo para generar la lista de links, tal vez usando [reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

**Comment by Hellacio** [comment]
Revisé esto de rapidito y no pude replicar el bug. No se cuando es cuando genera duplicados. Tal vez cuando se tiene una estructura en el README más compleja. 🤔

**Comment by afk-mario** [comment]
Al final de la función apliqué un truco de convertir el arreglo a un [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) y después regresarlo a arreglo, es un truco ahí medio rápido pero lo ideal es que desde el principio no hubiera duplicados, si agregas un `console.log(res)` [antes de esta línea](https://github.com/indi-es/estudios/blob/main/.github/site-checker/index.js#L38) puedes verlo.

**Comment by Hellacio** [comment]
Listo: https://github.com/indi-es/estudios/pull/8
Gracias por la aclaración @afk-mario. Al final no hubo necesidad de usar reduce. Creo que aún le podría dar una refactoreada para que quede mejor pero ahorita ya me dió flojera 😄.
