### ISSUE TITLE
Combinar developers.md -> estudios.json / Integrar Tags

### ISSUE THREAD

**Issue by afk-mario** [indi-es/estudios#34]
Mi propuesta es agregar un campo de tags a las entradas del JSON
```json
  {
         "nombre":"1 Simple Game",
         "pais":"México",
         "estado":"Jalisco",
         "ciudad":"Zapopan",
         "tipo":"Estudio",
         "inactivo":false,
         "ultima_vez_activo":"2021-02-21T23:54:02.104Z",
         "twitter":"https://twitter.com/1simplegame",
         "facebook":"https://www.facebook.com/1SimpleGame",
         "instagram":"",
         "website":"https://1simplegame.com/",
         "tags" : ["solodev", "freelance", "indi-es"]
      },
```

Y mostrarlas en el markdown

```md
 - [1 Simple Game](https://1simplegame.com/) - #solodev, #freelance, #indi-es
```

 - [1 Simple Game](https://1simplegame.com/) - #solodev, #freelance, #indi-es

**Comment by AlainPlusPlus** [comment]
Se supone que eso de tags es lo de `tipo : ["solodev", "freelance", "estudio"]`
¿Que querría decir **indi-es** y para que servirian los tags?

**Comment by AlainPlusPlus** [comment]
Estoy tratando de hacer una relacion a como lo tenemos ahora. Un estudio no tendría nunguno de esos tags a mi parecer `#solodev, #freelance, #indi-es`

**Comment by afk-mario** [comment]
Los tags solo son metadatos extra de cada entrada de la base de datos, en el caso de todos los que tenemos en `developers.md` los agregaríamos a la base de datos con el tag de `solodev` para poder mostrar de alguna manera que no son un estudio si no un individuo que hacen todo ellos. Use como ejemplo a 1 Simple Game porque es el primero de la lista pero no por que aplique a ese estudio.

El tag de indi-es lo pensaba yo como una manera de recalcar quienes son parte del discord de INDI-ES pero creo que eso lo podemos hacer ya que tengamos una representación mas amigable en la página web e invitar a los estudios que esten dentro del discord a avisarnos para agregarles el tag.

En el futuro creo que es una manera flexible y fácil de mantener de poder darle datos extra a la base de datos que permitirían hacer filtros u ordenamientos.

Podríamos hacerlo en lugar de un arreglo de tags un campo extra en cada objeto pero creo que con el arreglo de tags tenemos un poco más de flexibilidad.

**Comment by AlainPlusPlus** [comment]
Me parece muy buena idea. Ahora sólo pienso si tiene caso dejar el campo `tipo/type`. Se podría agregar `estudio` como un tag si eliminamos este campo.

**Comment by AlainPlusPlus** [comment]
Otra mejor forma de implementarse sería cambiar `estudios.json` a `developers.json` para incorporar la lista de ejemplo de`developers.md` (se tendría que quitar a las personas que ya trabajan para un estudio).

El final se podrían dejar los dos campos `tipo/type` y `tags` de la siguiente manera:

type : "studio" / "individual" / "services"
tags : ["solodev", "freelance", "indi-es"]

`services` incuiría empresas/personas que dan servicios relacionados al desarollo de juegos como publishers, artistas, músicos, etc.

**Comment by afk-mario** [comment]
@AlainPlusPlus me gusta esa solución solo sería actualizar las GH actions
